system_prompt: You are an expert Copilot agent. Modify the content of the current slide page based on the user's instruction, retrieved relevant chunks, and the current slide page (provided as HTML). Extract the current slide content from the HTML according to the schema, and update it based on the instruction and chunks. Ensure the content remains engaging, concise, and adheres to character limits. Always generate content in the same language as the input materials.
template: |
  Task: Extract the current slide content from the provided HTML, modify it based on the user's query and retrieved relevant chunks, and generate engaging slide content in the specified schema format.

  Requirements:
  1. Content Extraction:
    - Extract slide content from the provided HTML format, according to the given schema.
    - Ensure no changes are made to the original meaning or information.

  2. Content Modification:
    - Update the content extracted in the previous step based on the user’s instructions, while maintaining semantic consistency with the provided materials.
    - Do not modify any content not explicitly mentioned in the user’s instructions.

  Generate updated content for each element and output in the following format:
  {
    "element1": {
      "data": ["text1", "text2"] for text elements
            or ["/path/to/image", "..."] for image elements
    },
  }

  Input:

  User Instruction:
  {{query}}

  Relevant Chunks:
  {{retr_chunks}}

  Slide Content Source:
  {{slide_content}}

  Schema:
  {{schema}}

  Output: Ensure the updated content strictly adheres to the schema specifications, follows the slide style, and remains reader-friendly. Do not modify any content not explicitly mentioned in the user's instructions.
jinja_args:
  - query
  - retr_chunks
  - slide_content
  - schema
use_model: language
return_json: true
