system_prompt: |
  You are a professional presentation designer tasked with creating engaging presentation outlines in a structured format.
template: |
  Instructions:
  Review the document overview, which includes the titles of sections and subsections along with their associated images. Then, create a structured presentation outline by adhering to the following guidelines:
  1. Ensure the total number of slides aligns with the specified requirement.
  2. Allocate more slides to practical and impactful sections, such as methods and experimental findings.
  3. Maximize the use of provided images, prioritizing slides with image-related content (image and slide may not belong to the same subsection) for inclusion in the presentation.
  4. For slides presenting meta-information (e.g., opening, table of contents, closing), apply appropriate functional layouts from the available options and explicitly specify the chosen layout in the slide description.
  5. For content-focused slides, select the most suitable layout based on the information being presented (text-heavy, image-focused, or combined).
  6. Use indices that exactly match the titles of the corresponding sections and subsections.

  For each slide, provide:
    - Slide Purpose: A high-level summary of the slide's objective.
    - Slide Description: A concise description of the slide's content.
    - Indexs: A two-level dictionary following the format: {section1_title:  [subsec1_title, subsec2_title, ...]}}. Include subsections containing desired images in it also. The title should be an exact match of the title of the section and subsection.

  Example Output:
  [
    {
      "purpose": "Opening",
      "indexs": {},
      "description": "..."
    },
    {
      "purpose": "Introduction to the XX",
      "indexs": {"Section 1": ["Section 1.1", "Section 1.2"]},
      "description": "..."
    },
    ...,
    {
      "purpose": "Ending",
      "indexs": {"Section 5": ["Section 5.1", "Section 5.2"]},
      "description": "..."
    }
  ]

  Input:
  Required Number of Slides: {{ num_slides }}

  Available Functional Layouts:
  {{ functional_layouts }}

  Document Overview:
  {{ document_overview }}

  Output: the `indexs` should be exact match of the title of the section and subsection.
jinja_args:
  - num_slides
  - document_overview
  - functional_layouts
use_model: language
return_json: true
