name: Pull Request CI

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11", "3.12", "3.13"]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install git+https://github.com/Force1ess/python-pptx
                  pip install -e .
                  pip install -r test/requirements.txt

            - name: Run tests
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
              run: |
                  pytest test/test_apis.py -v
